### ISSUE TITLE
[SOLVED] help

### ISSUE THREAD

**Issue by GamingMetJayden** [CloneTrooper1019/Roblox-Plugins#1]
How do i get this on roblox studio? haha im new to github

**Comment by Jaguar-515** [comment]
You'll need Rojo in order to build the plugins into a model file & use them in Studio.

**Comment by Cakerdab** [comment]
> You'll need Rojo in order to build the plugins into a model file & use them in Studio.

How do I install Rojo?

**Comment by Jaguar-515** [comment]
> How do I install Rojo?


https://rojo.space/docs/installation/

**Comment by MrTuibr** [comment]
How do I add the plugin using the "Rojo" tool?

**Comment by ryanidk** [comment]
Ok, so here's a guide
First, install the rust programming language. [https://www.rust-lang.org/](https://www.rust-lang.org/)
Now, in command line, type `cargo install rojo --force`
It'll install.
Now, cd to the folder with the plugin. Likely C:\Users\yournamehere\Downloads\Roblox-Plugins-master\ToolGripEditor\now type `rojo build --output "$env:localappdata\Roblox\Plugins\ToolGripEditor.rbxmx"`
Done!

**Comment by Redknignt1109** [comment]
@ryanidk thats not working

**Comment by Thejumperdumper458** [comment]
> I already added the Rojo plugin How do I add the "Tool Grip Editor" plugin using the "Rojo" tool?

idk either bud
