### ISSUE TITLE
VMF importer not Compiling

### ISSUE THREAD

**Issue by matej118111** [CloneTrooper1019/Roblox-Plugins#10]
Yeah, i don't know how to fix this, i'm kinda stupid
![image](https://user-images.githubusercontent.com/51799660/148283367-7d2bb7ed-02fa-451f-8117-ab27fce300d8.png)

**Comment by AppleiLev5s** [comment]
btw im a programming idiot, can you tell me what do do if it finds no build task to do?

**Comment by AppleiLev5s** [comment]
oh, you just need rojo, find it in the bottom right corner, click it, select vmf importer and click the box icon, it should build the .rbxm file that you can drag into the plugins folder

**Comment by arefdsg** [comment]
you need msbuild

**Comment by matej118111** [comment]
thanks, sry for not replying i was busy with other things
