### ISSUE TITLE
Parent of workspace is locked

### ISSUE THREAD

**Issue by czctus** [CloneTrooper1019/Roblox-Plugins#13]
i tried adding the vmf importer but it did not work, i got rojo installed on vscode and roblox, tried connecting to the localhost and it didnt work with the error, "Parent of Workspace is locked."

**Comment by AppleiLev5s** [comment]
try building the plugin by opening rojo in vs code, and clicking the box icon next to default.project.json, you should get a .rbxm plugin ready to go in the workspace folder
