### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by vitKama** [CloneTrooper1019/Roblox-Plugins#2]
I don't know how to use it. Who can help

**Comment by cma07** [comment]
did u already get it

**Comment by vitKama** [comment]
I downloaded it, but then I don't know what to do

**Comment by cma07** [comment]
Here What I do : 
1. Extract the zip file
2. Place the Folder into PluginFolders in Roblox Studio
3. Restart the Roblox studio
Some of them are not working for me, but if you just want to use the ToolGripEditor
here's the Link : https://github.com/Anaminus/roblox-tool-grip-editor

--Good Luck--

**Comment by vitKama** [comment]
Thanks you
